# Generated by Django 5.2.8 on 2026-04-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
